name: uv run

on:
  workflow_call:
    inputs:
      command:
        description: Shell command to run after syncing dependencies.
        required: true
        type: string
      command_name:
        description: Display name for the final step.
        required: false
        type: string
        default: Run

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true  # cache deps
          cache-python: true  # cache Python installation
          version-file: "pyproject.toml"

      - name: Install dependencies
        run: uv sync

      - name: ${{ inputs.command_name }}
        run: ${{ inputs.command }}
